Feat/create quotation
GroupeNRM/Madera pull request #20
Opened 2021-03-10 17:07 UTC by Doe243

J'ai essayé de parcourir le code pour voir d'où venait l'erreur "Cannot read property 'status' of undefined" mais j'ai vraiment du mal, est-ce que vous pouvez me donner un coup de main parce que je galère sur ce point. 

![Capture d’écran 2021-03-10 180534](https://user-images.githubusercontent.com/27960839/110668113-3dcb2600-81cb-11eb-877f-96ae7f219fe4.png)

2021-03-10 18:13 UTC, Kayoshi-dev requested changes
Je t'ai fait un retour sur ton problème. Essaie de ne pas recréer une Pull Request à chaque fois stp et évite de commit les packages.json sauf en cas de modification de dependances.

2021-03-10 18:13 UTC, Kayoshi-dev commented on client/pages/creer-devis.vue
> +        <b-field label="Remise" class="column is-half" :type="validationFields.remise.status" :message="validationFields.remise.status === 'is-danger' ? validationFields.remise.message : ''">
Le problème vient de cette ligne et de la ligne 60.
Tu essaies d'accéder à la propriété status sur l'objet validationFields.remise mais il n'existe pas.
Il faut que dans ton objet ligne 133 tu rajoutes un nouvel objet remise.

2021-03-11 15:00 UTC, Doe243 commented on client/pages/creer-devis.vue
> +        <b-field label="Remise" class="column is-half" :type="validationFields.remise.status" :message="validationFields.remise.status === 'is-danger' ? validationFields.remise.message : ''">
Merci, c'est bon, c'est résolu

2021-03-11 15:02 UTC, SmashScharrer commented on client/pages/creer-devis.vue
> +        </b-field>
Calculer le prix TTC en back plutot que le mettre en dur ?

2021-03-11 15:02 UTC, SmashScharrer commented on client/pages/creer-devis.vue
> +      </div>
Au moment de créer le devis l'echlonnement doit etre à une valeur fixe (voir valeur dans le CDC)

2021-03-11 15:02 UTC, SmashScharrer commented on src/entity/Devis.ts
> +    echelonnement: string
Possibilite de rajouter valeur par defaut ? (Voir CDC + review precedente)

2021-03-11 15:02 UTC, SmashScharrer commented on src/entity/Devis.ts
> +    createdAt: Date
Valeur par défaut via une annotation ?

2021-03-11 22:51 UTC, Doe243 commented on client/pages/creer-devis.vue
> +        </b-field>
Je vais checké ça

2021-03-12 14:45 UTC, SmashScharrer commented
Mise à jour de la branche : 
- Modification du design du formulaire
- Modification de la requête POST

2021-03-17 23:20 UTC, Kayoshi-dev approved these changes
Ok

2021-03-17 23:20 UTC, merged